name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Install VLC (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install -y libvlc-dev libvlccore-dev

      - name: Install Haxelibs
        run: |
          haxelib install hxcpp
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib install flxanimate
          haxelib install json2object
          haxelib install polymod
          haxelib install hscript
          haxelib install hxvlc
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc

          haxelib install hmm
          haxelib run hmm install

      - name: Build Windows
        if: startsWith(matrix.os, 'windows')
        run: haxelib run lime build windows -D officialBuild

      - name: Build Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: haxelib run lime build linux -D officialBuild

      - name: Build macOS
        if: startsWith(matrix.os, 'macos')
        run: haxelib run lime build mac -D officialBuild

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'windows')
        with:
          name: windowsBuild
          path: export/release/windows/bin/*

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: linuxBuild
          path: export/release/linux/bin/*

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'macos')
        with:
          name: macBuild
          path: export/release/macos/bin/*

  Mobile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Setup Android SDK
        if: startsWith(matrix.os, 'ubuntu')
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          ndk: 25.1.8937393
          cmake: 3.22.1

      - name: Install Haxelibs
        run: |
          haxelib install hxcpp
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib install flxanimate
          haxelib install json2object
          haxelib install polymod
          haxelib install hscript
          haxelib install hxvlc
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc

          haxelib install hmm
          haxelib run hmm install

      - name: Configure Android
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true

      - name: Build Android
        if: startsWith(matrix.os, 'ubuntu')
        run: haxelib run lime build android -D officialBuild -ONLY_ARMV7

      - name: Build iOS
        if: startsWith(matrix.os, 'macos')
        run: haxelib run lime build ios -nosign -D officialBuild -DMOBILE_BUILD

      - name: Package IPA
        if: startsWith(matrix.os, 'macos')
        run: |
          cd export/release/ios/build/*-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r VsDave.ipa Payload

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'macos')
        with:
          name: iOSBuild
          path: export/release/ios/build/Release-iphoneos/*.ipa
